### ISSUE TITLE
Compile error - Crashlytics.CompareTo(Object): no suitable method found to override

### ISSUE THREAD

**Issue by manishkungwani** [azchohfi/Crashlytics.Droid#2]
Hi,
Unable to compile with the latest version of Xamarin.
Getting the error:

Crashlytics.CompareTo(Object): no suitable method found to override

Please let me know, how can this be worked around.

Thanks

**Comment by azchohfi** [comment]
I had no problem compiling it here.
I'm using the latest version: Xamarin.Android   6.0.3.5 (a94a03b)
I'm using VS2015 with Update 2.
Can you provide more info about your environment?

**Comment by azchohfi** [comment]
One other important information, I'm using JDK 1.7.0_71.

**Comment by manishkungwani** [comment]
@azchohfi tried it right now, same error. I'm using Xamarin Studio.
Here's my env:

```
Xamarin Studio Business
Version 5.10.3 (build 51)
Installation UUID: 2614921d-cafd-421c-87a0-704c120f6d85
Runtime:
    Microsoft .NET 4.0.30319.42000
    GTK+ 2.24.23 (MS-Windows theme)
    GTK# 2.12.30

Xamarin.Android
Version: 6.0.3.5 (Xamarin Business)
Android SDK: C:\Program Files\Android\android-sdk
        6.0    (API level 23)

SDK Tools Version: 25.0.10
SDK Platform Tools Version: 24 rc1
SDK Build Tools Version: 24 rc2


Java SDK: C:\Program Files\Java\jdk1.8.0_77
java version "1.8.0_77"
Java(TM) SE Runtime Environment (build 1.8.0_77-b03)
Java HotSpot(TM) 64-Bit Server VM (build 25.77-b03, mixed mode)

Build Information
Release ID: 510030051
Xamarin addins: ee5cfd3ecb6b20de47c1d25efb9a9abc101e8ce7
```

Here is the exact compile error:

`\Crashlytics.Droid\Crashlytics.Droid\Additions\Crashlytics.cs(29,29): Error CS0115: 'Crashlytics.CompareTo(Object)': no suitable method found to override (CS0115) (Crashlytics.Droid)`

**Comment by azchohfi** [comment]
You are not using the stable version of Android SDK, right?
Could you try using the stable version, not on the Preview Channel. I think that is related to your problem.
Could ou try that just to ensure that this is the problem? If so, we can report back to Xamarin because it may be a bug.

**Comment by azchohfi** [comment]
Btw, I tried to compile using Xamarin Studio and it did work. I'm using the stable version and JDK1.7.

**Comment by manishkungwani** [comment]
Perfect, worked like a charm with the stable version of Android.Thanks a lot 

Sent from Yahoo Mail on Android 

  On Sat, 2 Apr, 2016 at 2:56 am, Alexandre Zollinger Chohfinotifications@github.com wrote:  
Btw, I tried to compile using Xamarin Studio and it did work. I'm using the stable version and JDK1.7.

**Comment by azchohfi** [comment]
Perfect! That was easy.
