### ISSUE TITLE
Crash is not sending to crashlytics

### ISSUE THREAD

**Issue by chanti-github** [azchohfi/Crashlytics.Droid#3]
Hi,
I followed the steps as you mentioned for integration but i am not able to see the crashes in crashlytics.
any Idea please

**Comment by azchohfi** [comment]
Did you completed the steps to see create the project at Fabric's site? If so It should be working. At what step are you stuck?

**Comment by chanti-github** [comment]
Yes I created the project on fabric and completed all steps even it is not
capturing the crashes ..

**Comment by azchohfi** [comment]
I have no idea... It should be working just as any other project that does work. Can you provide a min repro project?

**Comment by Miiite** [comment]
I also have nothing displaying in the crashlytics dashboard.

I did everything in android studio to create the project (I can see it), my package name is correct, and so is the api key.

Yet if I trigger a NullReferenceException and let the app crash, I never get any data in Crashlytics dashboard

**Comment by azchohfi** [comment]
Damn... I'll investigate this ASAP. Sorry for the inconvenience.

**Comment by Miiite** [comment]
I know that Xamarin.Insights is forced to subscribe to various event source, to be able to cover every single potential crash source (from async Tasks, android code etc).

Maybe something similar is required when using crashlytics android ?
Have you looked at the iOS version of the Binding project ? I saw one on Nuget

**Comment by azchohfi** [comment]
I've found the bug... Now the keyname changed, it should be:
meta-data android:name="**io.fabric.ApiKey**"
I'll update the docs.

**Comment by Miiite** [comment]
Nice ! I'll try that as soon as I can
