### ISSUE TITLE
I can not show crash in dashboard pls help

### ISSUE THREAD

**Issue by ShraddhaGadesha** [azchohfi/Crashlytics.Droid#6]
Crash is not sending to crashlytics .I have intergrated the code but when my app got crash ,crash is not displaying in dashboard in fabric

**Comment by joshuatantonflynn** [comment]
I am also having this issue. fabric project is created through a dummy android studio project. I enter all necessary code into xamaran. crash sends nothing to fabric.

**Comment by azchohfi** [comment]
I updated to the latest version (2.8.0) and added a sample app so you can make sure you added everything needed. Let me know if the issue persists, but I could make it work with the old version, just following the steps.
